#####################
### Staff Tracker ###
###  by TuffDev   ###
#####################
####Enable  MYSQL####
#####################
Enable MySQL: false
#####################
MySQL Details:
 host: "127.0.0.1"
 port: "3306"
 user: ""
 password: ""
 database: ""
#####################
